sudo: required

language: sh

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal

services:
  - docker

script:
  - if [[ -n ${TRAVIS_TAG} ]]; then ./run "$TRAVIS_TAG"; fi

deploy:
  provider: releases
  skip_cleanup: true
  file:
    - idris-${TRAVIS_TAG#v}-amd64.tar.gz
    - idris-${TRAVIS_TAG#v}-amd64.deb
  on:
    tags: true
  api_key:
    secure: E7iF2q+BPDKulZJXCE/EJDR8Wpzyn+aUl5Q6xulgZv8siOfi7s/gY6rLxgsEQHhBxX/V1/aXnBVaol9hlIng1P0sNTuWBAY1ZClXIDTb/tE42t9Wb3tP/bgbEYqoVbOq3uI1ZOZMMTfZpKJfcqCegtU5pYKWbYKK6pGRaHXtI9C0dPz89EqIO7YQJlzefvc7bJ/aLm64So6Z2yK2vkr905tZexC/K1rdbZEtzhNCHIe6ol52TNm1MPw/m38s2hqh9qql9gwJvzd23Y7A3EsImLclO4Eo9vBYIwHKeezs1F1jvHPqSQ8/Q43cpvbJVzK/N+SRhVcD9wbawhZ6BnKGDGL/OWfLwMyONDeEpKgGICKpAxpPucJyRZb7SoknKGIbf/y3jVDcdRRDVF6EeRoQuDRxmdTotGSWH/6kyGgRpw5vf0zcpIiCrFUxxjiZ7ECQcBWzsNn1BeEJxM6jQASBmzK/LPg6EhNXWKEm5J96KB+WJi71LrLy5Zd7Pj2iOtQGFkkuLr+KH/fyiEoImaGQ69socKoiOXvlyLpmVjFsKz5Gf9uTo91n5uVXGhGjOkny6UgcJPNPmWLmTE0jnolafML+6vb4mjJ16445sDX1yrCtY5trdELqYuiuF3BwIAMfzlBBB8QJTBvfCo6o3/9O62TQNFXcQQ3xXuf/OLQYnBM=
